### ISSUE TITLE
can not open "https://github.com/aquasecurity/vuln-list/"

### ISSUE THREAD

**Issue by zhuxindong** [aquasecurity/vuln-list-update#210]
the page [https://github.com/aquasecurity/vuln-list/](https://github.com/aquasecurity/vuln-list/%E2%80%9D) got status 500 in anytime
![image](https://github.com/aquasecurity/trivy/assets/24989246/899c10b6-ae84-4453-9e77-fb9a32ce0a4e)

**Comment by afdesk** [comment]
thanks for the report! 
yes, it's a known issue
we're on it right now

**Comment by beltran-rubo** [comment]
Any progress on it? Thanks

**Comment by afdesk** [comment]
we're still working on it.

There was a simple solution, 
unfortunately it works for my fork (https://github.com/afdesk/vuln-list), but doesn't help the main repository.

now @knqyf263 looks for more comprehensive solution

**Comment by bbossola** [comment]
Any progress on this? Can we help in any way?

**Comment by knqyf263** [comment]
The GitHub support is fixing that now. Meanwhile, we're using the backup.
https://github.com/aquasecurity/vuln-list-reserve

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy-db/issues/333
