### ISSUE TITLE
feat(go): add Go module vulns (stdlib) from go-vulndb

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/vuln-list-update#288]
## Description
See https://github.com/aquasecurity/trivy/issues/4133#issuecomment-2068626003

**Comment by knqyf263** [comment]
We dropped go-vulndb for some reason in https://github.com/aquasecurity/trivy-db/pull/330. I feel like we need to use GHSA for Go module vulnerabilities and go-vulndb for Go runtime/toolchain vulnerabilities.

**Comment by DmitriyLewen** [comment]
IIRC there are problems with severities (go-vulndb's advisories don't contain severity information) and duplicates (Trivy's reports included two same vulnerabilities GO-xxx-xxx and CVE-xxxx-xxxx (or GHSA)).

**Comment by knqyf263** [comment]
>go-vulndb's advisories don't contain severity information

Oh, I completely forgot about it. Yes, it seems like go-vulndb still doesn't have severities.

**Comment by DmitriyLewen** [comment]
I checked some recent advisories and it looks like go-vulndb tries to always add CVE numbers.
Therefore, we will simply take the severity from the NVD.

**Comment by knqyf263** [comment]
Cool. The remaining problem is de-duplication.

**Comment by DmitriyLewen** [comment]
> it looks like go-vulndb tries to always add CVE numbers.

This should help too.
If all go-vulndb advisories contain CVEs, we will only store CVEs and will not receive duplicates.

**Comment by DmitriyLewen** [comment]
I also realized that `go-vulndb` has [repository on github](https://github.com/golang/vulndb/tree/d97490989e7446ae88eed39434d73d454ef14426/data/osv), so we don't need to store advisories in `vuln-list`, we can work directly with that repository in Trivy-db 😅

**Comment by knqyf263** [comment]
Yes, and it's the OSV format. It's easy to parse it as we already have [the OSV implementation](https://github.com/aquasecurity/vuln-list-update/blob/5a4b5af58232dfa3e74749c753d77c60a62c178e/osv/osv.go).

**Comment by knqyf263** [comment]
>If all go-vulndb advisories contain CVEs, we will only store CVEs and will not receive duplicates.

But we store duplicated advisories in the database. Am I correct?

**Comment by DmitriyLewen** [comment]
right 😞

**Comment by DmitriyLewen** [comment]
I checked and we will get 98 duplicates:
```
➜  grep -r '"name": "stdlib",' ./osv | sort | uniq| wc -l
      98
```

**Comment by knqyf263** [comment]
It seems like we can list the standard packages.
https://pkg.go.dev/golang.org/x/tools/go/packages#Load

The easiest way is we replace the standard packages with `stdlib`.
https://github.com/github/advisory-database/blob/6a39d01a5988c773309b1f80c8863d2f5d18896f/advisories/github-reviewed/2024/04/GHSA-4v7x-pqxf-cx7m/GHSA-4v7x-pqxf-cx7m.json#L21C10-L21C14

**Comment by knqyf263** [comment]
Another problem:
GHSA doesn't eagerly review Go runtime/toolchain vulnerabilities. Even vulnerabilities disclosed more than a year ago are still "unreviewed".
https://github.com/advisories/GHSA-vvjp-q62m-2vph
https://github.com/advisories/GHSA-89mw-w342-mqrr

**Comment by knqyf263** [comment]
I decided to directly consume [the repository](https://github.com/golang/vulndb). We don't need to update vuln-list-update.

**Comment by DmitriyLewen** [comment]
> Another problem:
GHSA doesn't eagerly review Go runtime/toolchain vulnerabilities. Even vulnerabilities disclosed more than a year ago are still "unreviewed".

Then we need to use go-vulndb (for Go module vulnerabilities) + GHSA (for Go deps)
