### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/vuln-list-update#36]
Now, vuln-list-update uses TravisCI. We'll migrate CI to GitHub Actions.
https://github.com/aquasecurity/vuln-list-update/blob/master/.travis.yml

**Comment by knqyf263** [comment]
@rahul2393

**Comment by rahul2393** [comment]
@knqyf263 Manual workflow working and pushing to repo [here](https://github.com/rahul2393/vuln-list)
https://github.com/rahul2393/vuln-list-update/runs/865003803?check_suite_focus=true
