### ISSUE TITLE
Check for edge (master) branch of alpine

### ISSUE THREAD

**Issue by forty** [aquasecurity/vuln-list-update#39]
I think it would be worth checking the edge branch of alpine (and not only the -stable branches). As a matter of fact, some vulns can only be found there.

*Concrete example:*

latest Alpline (3.12) ships nodejs 12.17.0. This version is vulnerable, but is not detected as such in trivy as the CVEs are only listed in the master branch for now https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/nodejs/APKBUILD

**Comment by knqyf263** [comment]
We migrated to a new secdb.
https://secdb.alpinelinux.org/

You can discuss it here.
https://gitlab.alpinelinux.org/alpine/infra/docker/secdb/-/issues

Thanks.
