### ISSUE TITLE
Migrate Red Hat Security Data API to OVAL v2

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/vuln-list-update#45]
We're using two data sources for Red Hat

- OVAL v2
  - https://github.com/aquasecurity/vuln-list-update/blob/master/oval/redhat/redhat.go#L24
  - for fixed vulnerabilities
  - there is a patch for each vulnerability
- Red Hat Security Data API - CVE
  - https://access.redhat.com/documentation/en-us/red_hat_security_data_api/1.0/html-single/red_hat_security_data_api/index#cve
  - for unfixed vulnerabilities
  - there is no patch

Red Hat is planning to deprecate Security Data API and they already added the information regarding unfixed vulnerabilities to OVAL v2. It means we can discard Security Data API and use only OVAL v2. We have to change `redhat.go` to parse unfixed vulnerabilities as well.
https://github.com/aquasecurity/vuln-list-update/blob/master/oval/redhat/redhat.go

**Comment by knqyf263** [comment]
@rahul2393 Could you look into it?

**Comment by rahul2393** [comment]
Sure
