### ISSUE TITLE
Failing build on the master

### ISSUE THREAD

**Issue by neha-viswanathan** [aquasecurity/vuln-list-update#53]
The CI on the `master` branch has been failing for a while now due to invalid credentials:

```
2020/07/13 14:26:10 remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/aquasecurity/vuln-list.git/'
2020/07/13 14:26:10 failed to git push: error in git push: failed to exec: exit status 128
```

**Comment by knqyf263** [comment]
What do you mean? It looks working.
![image](https://user-images.githubusercontent.com/2253692/96080527-eb0d6c80-0ebf-11eb-8877-b3f5acde45b8.png)

**Comment by neha-viswanathan** [comment]
<img width="1058" alt="Screen Shot 2020-10-14 at 10 31 51 PM" src="https://user-images.githubusercontent.com/12013126/96080947-20d53580-0e6d-11eb-8f3f-49936bf162ed.png">
 I meant on Travis

**Comment by knqyf263** [comment]
I see. We migrated to GitHub Actions and don't use TravisCI now.
https://github.com/aquasecurity/vuln-list-update/issues/36
