### ISSUE TITLE
Support safety-db

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/vuln-list-update#57]
Currently, `trivy-db` downloads `pyupio/safety-db` directly.
https://github.com/aquasecurity/trivy-db/blob/master/Makefile#L73

But if `safety-db` changes the format, it causes the DB build to fail. We should parse `safety-db` and commit it to `vuln-list` once.

The directory structure should be like the following.

- python
  - safety-db
    - django
      - pyup.io-25694.json
      - pyup.io-25695.json
    - django-access-tokens

**Comment by knqyf263** [comment]
@rahul2393 Could you work on it?

**Comment by rahul2393** [comment]
Ack
